networks:
  test_network:
    driver: bridge

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/api
    command: bash -c "poetry run python manage.py runserver 0.0.0.0:8000"
    networks:
      - test_network
  web:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/front
      - /front/node_modules
    command: bash -c "npm run dev-docker"
    networks:
      - test_network
    environment:
      API_URL: host.docker.internal:8000
      KEYCLOAK_URL: host.docker.internal:8080
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - "8080:8080"
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - test_network